version: 2.1

jobs:
  saluda: # nombre del job
    docker: # tipo de ejecución
    - image: cimg/base:stable # entorno o nombre de la imagen
    steps: # pasos a seguir 
    - run: echo "Hola, mundo!" # por ejemplo ejecutar un echo dentro de ubuntu
  adios:
    docker:
    - image: cimg/base:stable
    steps:
    - run: echo "Adiós, mundo!"
  testing:
    docker:
    - image: cimg/base:stable
    steps:
    - run : echo "Testing"

workflows: # flujo de trabajo
  hello: # nombre del flujo de trabajo
    jobs: # ejecucion de los jobs antes creados lo concurrentemente.
    - saluda
    - adios

  adios:
    jobs:
    - saluda
    - adios:
        requires:
        - saluda
  test:
    jobs:
    - saluda
    - adios:
        requires:
        - saluda
    - testing:
        type: approval
        requires:
        - adios
