version: 2.1

jobs:
  deploy:
    docker:
    - image: circleci/python:3.10

    steps:
    - checkout

    # Copiar la clave SSH al contenedor
    - add_ssh_keys:
        fingerprints:
        - "SHA256:NbGN39KhIfZNfq6NvZ5DdI56wIgyLnZ/RjPv2BgG4UA"
    # Ejecutar el despliegue en la instancia EC2
    - run:
        name: Deploy to EC2
        command: |
          "mkdir app && cd /app && git clone git@github.com:luiss1981/hello-world.git && docker compose up -d --build"

workflows:
  deploy:
    jobs:
    - deploy
   
