version: 2.1

jobs:
  build:
    docker:
    - image: circleci/python:3.10

    steps:
    - checkout

    add_ssh_keys:
      fingerprints:
        - "SHA256:NbGN39KhIfZNfq6NvZ5DdI56wIgyLnZ/RjPv2BgG4UA"
      run:
        echo "Add your SSH key fingerprints here"


workflows:
  build-and-deploy:
    jobs:
    - deploy

