version: 2.1

jobs:
  deploy:
    docker:
    - image: circleci/python:3.10

    steps:
    - checkout

    # Copiar la clave SSH al contenedor
    - add_ssh_keys:
        fingerprints:
        - "SHA256:NbGN39KhIfZNfq6NvZ5DdI56wIgyLnZ/RjPv2BgG4UA"
    # Ejecutar el despliegue en la instancia EC2
    - run:
        name: Deploy to EC2
        command: |
          ssh -i /home/luis/Descargas/pruebas_keys_luis.pem ubuntu@13.39.107.4 "echo hola mundo"

workflows:
  deploy:
    jobs:
    - deploy
   
